FORMAT: 1A
HOST: http://local.lepton.co

# SpiritLabs API
The SpiritLabs API allows prayer and giving on this Lepton and Prayer platform.

# Group Account
The account is the logged in end user, but this API will not fail when they are logged out, as often defaults are allowed.

## Account Details [/app_test.php/api/account]
The detail about an account, which still works if not logged in.

### Retreive Account [GET]
+ Request (application/json)

    + Header
            
            Cookie: PHPSESSID=suf8n31ca43dc4ne5h38ok0da5

+ Response 200 (application/json)

        {
            "isLoggedIn": true,
            "account": {
                "id": 1,
                "email": "nathan+42@eit.co.nz",
                "firstName": "Nathan",
                "lastName": "O'Hanlon",
                "enabled": true,
                "prayer_card_collection_code": {},
                "facebook_id": 718469082
            }
        }


## Accounts Current Quiet Time [/app_test.php/api/account/quiettime]
A Quiet Time holds Prayer Today Cards. Each has a prayerCountForAccount number that tells us how many times this user has prayed for a Prayer Today Card.
This view of the Quiet Time is minimal and only focusses on parts specific to the currently logged in account.

### Retrieve QuietTimes Prayer Detail [GET]
+ Request (application/json)

    + Header

            Cookie: PHPSESSID=suf8n31ca43dc4ne5h38ok0da5

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "First Test Quiet Time",
            "prayerTodayCards": [
                {
                    "id": 1,
                    "prayerCountForAccount": 0
                },
                {
                    "id": 2,
                    "prayerCountForAccount": 3
                },
                {
                    "id": 3,
                    "prayerCountForAccount": 3
                },
                {
                    "id": 4,
                    "prayerCountForAccount": 3
                },
                {
                    "id": 5,
                    "prayerCountForAccount": 0
                },
                {
                    "id": 6,
                    "prayerCountForAccount": 0
                },
                {
                    "id": 7,
                    "prayerCountForAccount": 0
                },
                {
                    "id": 8,
                    "prayerCountForAccount": 0
                },
                {
                    "id": 9,
                    "prayerCountForAccount": 0
                },
                {
                    "id": 10,
                    "prayerCountForAccount": 0
                },
                {
                    "id": 11,
                    "prayerCountForAccount": 0
                }
            ],
            "prayerTodayCardCount": 11,
            "organisation": {
                "id": 2,
                "name": "St George's"
            },
            "adminAccount": {
                "id": 1
            }
        }


# Group Prayer Updates
PrayerUpdates can be made for many types of resource, including accounts, organisations, churches, bible readings, etc.

## Prayer Update Collection [/app_test.php/api/prayer/updates]
### List all Prayer Updates for a logged in user [GET]

+ Request (application/json)

    + Header

            Cookie: PHPSESSID=suf8n31ca43dc4ne5h38ok0da5
            Accept: application/json

+ Response 200 (application/json)

        {
          "total": 3,
          "limit": 10,
          "data": [
            {
              "id": 2,
              "account": {
                "id": 1,
                "firstName": "Nathan",
                "lastName": "O'Hanlon",
                "facebook_id": 718469082
              },
              "content": "Second for user 1 prayer update",
              "comments": [
                {
                  "id": 1,
                  "account": {
                    "id": 1,
                    "firstName": "Nathan",
                    "lastName": "O'Hanlon",
                    "facebook_id": 718469082
                  },
                  "content": "First test prayer comment",
                  "createdAt": "2014-08-21T15:30:09+0000"
                },
                {
                  "id": 2,
                  "account": {
                    "id": 1,
                    "firstName": "Nathan",
                    "lastName": "O'Hanlon",
                    "facebook_id": 718469082
                  },
                  "content": "Second test prayer comment",
                  "createdAt": "2014-08-21T15:30:09+0000"
                }
              ],
              "createdAt": "2014-08-21T15:30:09+0000"
            },
            {
              "id": 1,
              "account": {
                "id": 1,
                "firstName": "Nathan",
                "lastName": "O'Hanlon",
                "facebook_id": 718469082
              },
              "content": "Some test prayer update",
              "organisationBase": {
                "id": 1,
                "name": "St George's",
                "countryCode": "GB",
                "colour": "38373E",
                "createdAt": "2014-08-21T15:30:09+0000",
                "updatedAt": "2014-08-21T15:30:09+0000",
                "isActive": true
              },
              "comments": [],
              "createdAt": "2014-08-21T15:30:09+0000"
            }
          ]
        }

## PrayerUpdate Collection with Parameters [/app_test.php/api/prayer/updates?object_id=1&object_type=account&limit=1]
### List all PrayerUpdates for a given account [GET]
There will be the ability to have object_type of 'account' (default), 'organisation', or 'church'. For now just 'account' is supported.

The limit defaults to 10 if not specified. The most recent prayer update will be returned if specified as 1.

+ Request (application/json)

    + Header

            Cookie: PHPSESSID=suf8n31ca43dc4ne5h38ok0da5
            Accept: application/json

+ Response 200 (application/json)

        {"total": 4, "limit": 1, "data": [
            {
                "id": 2,
                "account": {
                    "id": 1,
                    "firstName": "Nathan",
                    "lastName": "O'Hanlon",
                    "facebook_id": 718469082
                },
                "content": "Second for user 1 prayer update",
                "comments": [
                    {
                        "id": 1,
                        "account": {
                            "id": 1,
                            "firstName": "Nathan",
                            "lastName": "O'Hanlon",
                            "facebook_id": 718469082
                        },
                        "content": "First test prayer comment",
                        "createdAt": "2014-08-05T13:07:22+0000"
                    },
                    {
                        "id": 2,
                        "account": {
                            "id": 1,
                            "firstName": "Nathan",
                            "lastName": "O'Hanlon",
                            "facebook_id": 718469082
                        },
                        "content": "Second test prayer comment",
                        "createdAt": "2014-08-05T13:07:22+0000"
                    }
                ],
                "createdAt": "2014-08-05T13:07:22+0000"
            }
        ]}

### Create a PrayerUpdate [POST]
+ Request (application/json)

    + Header

            Cookie: PHPSESSID=suf8n31ca43dc4ne5h38ok0da5

    + Body

            { "content": "A new prayer update" }

+ Response 200 (application/json)

        {"id": 18, "account": {
            "id": 217,
            "firstName": "Nathan",
            "lastName": "O'Hanlon",
            "facebook_id": 718469082
        }, "content": "A new prayer update", "comments": [], "createdAt": "2014-07-09T10:48:58+0000"}

## Single PrayerUpdate [/app_test.php/api/prayer/updates/{id}]
A single PrayerUpdate object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the PrayerUpdate to perform action with. Has example value.

### Retrieve a PrayerUpdate [GET]
+ Request (application/json)

    + Header

            Cookie: PHPSESSID=suf8n31ca43dc4ne5h38ok0da5

+ Response 200 (application/json)

        {"id": 1, "account": {
            "id": 1,
            "firstName": "Nathan",
            "lastName": "O'Hanlon",
            "facebook_id": 718469082
        }, "content": "Some test prayer update", "organisationBase": {
            "id": 1,
            "name": "St George's",
            "countryCode": "GB",
            "colour": "38373E",
            "createdAt": "2014-08-21T15:30:09+0000",
            "updatedAt": "2014-08-21T15:30:09+0000",
            "isActive": true
        }, "comments": [], "createdAt": "2014-08-21T15:30:09+0000"}

### Update a PrayerUpdate [PATCH]
+ Request (application/json)

    + Header
    
            Cookie: PHPSESSID=suf8n31ca43dc4ne5h38ok0da5

    + Body
    
            { "op": "replace", "path": "content", "value": "An updated prayer update" }

+ Response 204 (text/plain; charset=UTF-8)

### Remove a PrayerUpdate [DELETE]

+ Response 204 (text/plain; charset=UTF-8)










# Group Comments
PrayerUpdateComment related resources of the **PrayerUpdateComment API**

## Comments Collection [/app_test.php/api/prayer/updates/2/comments]
### List all Comments for a PrayerUpdate [GET]
+ Request (application/json)

    + Header

            Cookie: PHPSESSID=g89b82eti4oeu6v0c05rq8qng5
            Accept: application/json

+ Response 200 (application/json)

        {
            "id": 3,
            "account": {
                "id": 1
            },
            "prayerUpdate": {
                "id": 2
            },
            "content": "A new comment for prayer update 2",
            "createdAt": "2014-10-02T16:36:31+0000"
        }

### Create a Comment [POST]
+ Request (application/json)

    + Header

            Cookie: PHPSESSID=g89b82eti4oeu6v0c05rq8qng5
            Accept: application/json
            
    + Body
    
            { "content": "A new comment for prayer update 2" }

+ Response 200 (application/json)

        {
            "id": 3,
            "account": {
                "id": 1
            },
            "prayerUpdate": {
                "id": 2
            },
            "content": "A new comment for prayer update 2",
            "createdAt": "2014-10-02T16:39:34+0000"
        }

## Comment [/app_test.php/api/prayer/updates/2/comments/{id}]
A comment object with all of its details

+ Parameters
    + id (required, number, `2`) ... Numeric `id` of the Comment to perform action with. Has example value.

### Retrieve a Comment [GET]
+ Response 200 (application/json)

        {
            "id": 2,
            "prayerUpdate": {
                "id": 2
            },
            "content": "Second test prayer comment",
            "createdAt": "2014-10-02T13:56:34+0000"
        }

### Update a Comment [PATCH]
+ Request (application/json)

    + Header
    
            Cookie: PHPSESSID=g89b82eti4oeu6v0c05rq8qng5

    + Body
    
            { "op": "replace", "path": "content", "value": "An updated comment for prayer update 1" }

+ Response 204

### Remove a Comment [DELETE]
+ Response 204


# Group QuietTime
QuietTime API retreives detail on a grouping of PrayerTodayCards, with a name and later an author.

## QuietTime Collection [/app_test.php/api/prayer/quiettimes]
### List all QuietTime objects [GET]

+ Request (application/json)

    + Header
    
            Cookie: PHPSESSID=g89b82eti4oeu6v0c05rq8qng5
            Accept: application/json

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "First Test Quiet Time",
                "prayerTodayCardCount": 11,
                "organisation": {"id": 2, "name": "St George's"}
            },
            {
                "id": 2,
                "name": "Second Test Quiet Time",
                "prayerTodayCardCount": 3,
                "organisation": {"id": 2, "name": "St George's"}
            }
        ]

## Single QuietTime [/app_test.php/api/prayer/quiettimes/{id}]
A single QuietTime object with all its details

+ Parameters

    + id (required, number, `1`) ... Numeric `id` of the QuietTime to perform action with. Has example value.

### Retrieve a single QuietTime [GET]
+ Request (application/json)

    + Header

            Cookie: PHPSESSID=g89b82eti4oeu6v0c05rq8qng5

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "First Test Quiet Time",
            "prayerTodayCardCount": 11,
            "organisation": {
                "id": 2,
                "name": "St George's",
                "countryCode": "GB",
                "colour": "38373E",
                "createdAt": "2014-10-01T08:46:05+0000",
                "updatedAt": "2014-10-01T08:46:05+0000",
                "isActive": true
            },
            "adminAccount": {"id": 1}
        }

# Group PrayerTodayCard
PrayerTodayCard API retreives the PrayerTodayCards associated with a QuietTime.

## PrayerTodayCard Collection [/app_test.php/api/prayer/quiettimes/{quiettime_id}/todays]

+ Parameters

    + quiettime_id (required, number, `1`) ... Numeric `id` of the QuietTime to perform action with. Has example value.


### List all PrayerTodayCard objects for logged in account [GET]

+ Request (application/json)

    + Header

            Cookie: PHPSESSID=g89b82eti4oeu6v0c05rq8qng5
            Accept: application/json

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "account": {"id": 1, "firstName": "Nathan", "lastName": "O'Hanlon", "facebook_id": 718469082},
                "prayerBlock": {
                    "id": 1,
                    "text": "Do not judge, or you too will be judged. For in the same way you judge others, you will be judged, and with the measure you use, it will be measured to you.",
                    "prayerUpdate": false,
                    "bookName": "Matthew",
                    "chapterFrom": 7,
                    "chapterTo": 7,
                    "verseFrom": 1,
                    "verseTo": 2
                },
                "isGivable": false,
                "prayerCount": 0,
                "type": "bible",
                "baseType": "prayer_block"
            },
            {
                "id": 2,
                "account": {"id": 1, "firstName": "Nathan", "lastName": "O'Hanlon", "facebook_id": 718469082},
                "prayerUpdate": {
                    "id": 2,
                    "content": "Second for user 1 prayer update",
                    "prayerCount": 2,
                    "comments": [
                        {
                            "id": 1,
                            "account": {"id": 1, "firstName": "Nathan", "lastName": "O'Hanlon", "facebook_id": 718469082},
                            "content": "First test prayer comment",
                            "createdAt": "2014-10-02T13:56:34+0000"
                        },
                        {
                            "id": 3,
                            "account": {"id": 1, "firstName": "Nathan", "lastName": "O'Hanlon", "facebook_id": 718469082},
                            "content": "A new comment for prayer update 2",
                            "createdAt": "2014-10-02T15:58:36+0000"
                        }
                    ],
                    "createdAt": "2014-10-02T13:56:34+0000"
                },
                "isGivable": false,
                "prayerCount": 2,
                "type": "prayer_update",
                "baseType": "prayer_update"
            },
            {
                "id": 3,
                "account": {"id": 1, "firstName": "Nathan", "lastName": "O'Hanlon", "facebook_id": 718469082},
                "project": {
                    "id": 1,
                    "name": "'Older brother\/sister' mentors for HIV+ children",
                    "summary": "The vision for this project is to train up and equip young adults to become 'big brothers or sisters' to mentor HIV+ children in need.",
                    "thankYou": "raise up and and train 20 older brothers and sisters to mentor HIV+ children in Cambodia.",
                    "goalAmount": 460,
                    "raisedAmount": 0,
                    "colour": "47878E",
                    "countryEffectedCode": "KH",
                    "isChurch": false,
                    "organisation": {
                        "type": "organisation",
                        "UUID": "organisation_1",
                        "id": 1,
                        "name": "Tearfund",
                        "description": "When disasters strike, Tearfund responds quickly. Inspired by the example of Jesus, we are working to tackle material and spiritual poverty in more than 50 countries from the inside out.",
                        "administratorEmail": "peter.yates@tearfund.org",
                        "addressLineOne": "100 Church Road",
                        "city": "Teddington",
                        "postalCode": "TW11 8QE",
                        "telephoneNumber": "02089437973",
                        "mobileNumber": "07576016847",
                        "countryCode": "GB",
                        "hasLogo": true,
                        "hasImage": true,
                        "createdAt": "2013-10-02T13:56:34+0000",
                        "updatedAt": "2014-10-02T13:56:34+0000",
                        "isActive": true
                    },
                    "created": "2014-10-02T13:56:34+0000",
                    "updatedAt": "2014-10-02T13:56:34+0000",
                    "IndividualsSupporting": []
                },
                "isGivable": false,
                "prayerCount": 1,
                "type": "project",
                "baseType": "project"
            },
            {
                "id": 4,
                "account": {"id": 1, "firstName": "Nathan", "lastName": "O'Hanlon", "facebook_id": 718469082},
                "organisation": {
                    "type": "organisation",
                    "UUID": "organisation_1",
                    "id": 1,
                    "name": "Tearfund",
                    "description": "When disasters strike, Tearfund responds quickly. Inspired by the example of Jesus, we are working to tackle material and spiritual poverty in more than 50 countries from the inside out.",
                    "administratorEmail": "peter.yates@tearfund.org",
                    "addressLineOne": "100 Church Road",
                    "city": "Teddington",
                    "postalCode": "TW11 8QE",
                    "telephoneNumber": "02089437973",
                    "mobileNumber": "07576016847",
                    "countryCode": "GB",
                    "hasLogo": true,
                    "hasImage": true,
                    "createdAt": "2013-10-02T13:56:34+0000",
                    "updatedAt": "2014-10-02T13:56:34+0000",
                    "isActive": true
                },
                "isGivable": false,
                "prayerCount": 1,
                "type": "organisation",
                "baseType": "organisation"
            },
            {
                "id": 5,
                "account": {"id": 1, "firstName": "Nathan", "lastName": "O'Hanlon", "facebook_id": 718469082},
                "organisation": {
                    "id": 2,
                    "name": "St George's",
                    "description": "St George's church is...",
                    "administratorEmail": "john.valentine@stgholborn.org",
                    "addressLineOne": "Queen Square",
                    "city": "London",
                    "postalCode": "WC1N 3AH",
                    "telephoneNumber": "02074044407",
                    "countryCode": "GB",
                    "colour": "38373E",
                    "hasLogo": true,
                    "hasImage": true,
                    "createdAt": "2014-10-02T13:56:34+0000",
                    "updatedAt": "2014-10-02T13:56:34+0000",
                    "isActive": true
                },
                "isGivable": false,
                "prayerCount": 1,
                "type": "church",
                "baseType": "organisation"
            },
            {
                "id": 6,
                "account": {"id": 1, "firstName": "Nathan", "lastName": "O'Hanlon", "facebook_id": 718469082},
                "organisation": {
                    "type": "organisation",
                    "UUID": "organisation_1",
                    "id": 1,
                    "name": "Tearfund",
                    "description": "When disasters strike, Tearfund responds quickly. Inspired by the example of Jesus, we are working to tackle material and spiritual poverty in more than 50 countries from the inside out.",
                    "administratorEmail": "peter.yates@tearfund.org",
                    "addressLineOne": "100 Church Road",
                    "city": "Teddington",
                    "postalCode": "TW11 8QE",
                    "telephoneNumber": "02089437973",
                    "mobileNumber": "07576016847",
                    "countryCode": "GB",
                    "hasLogo": true,
                    "hasImage": true,
                    "createdAt": "2013-10-02T13:56:34+0000",
                    "updatedAt": "2014-10-02T13:56:34+0000",
                    "isActive": true
                },
                "isGivable": false,
                "prayerCount": 0,
                "type": "organisation",
                "baseType": "organisation"
            },
            {
                "id": 7,
                "account": {"id": 1, "firstName": "Nathan", "lastName": "O'Hanlon", "facebook_id": 718469082},
                "organisation": {
                    "type": "organisation",
                    "UUID": "organisation_1",
                    "id": 1,
                    "name": "Tearfund",
                    "description": "When disasters strike, Tearfund responds quickly. Inspired by the example of Jesus, we are working to tackle material and spiritual poverty in more than 50 countries from the inside out.",
                    "administratorEmail": "peter.yates@tearfund.org",
                    "addressLineOne": "100 Church Road",
                    "city": "Teddington",
                    "postalCode": "TW11 8QE",
                    "telephoneNumber": "02089437973",
                    "mobileNumber": "07576016847",
                    "countryCode": "GB",
                    "hasLogo": true,
                    "hasImage": true,
                    "createdAt": "2013-10-02T13:56:34+0000",
                    "updatedAt": "2014-10-02T13:56:34+0000",
                    "isActive": true
                },
                "isGivable": false,
                "prayerCount": 0,
                "type": "organisation",
                "baseType": "organisation"
            },
            {
                "id": 8,
                "account": {"id": 1, "firstName": "Nathan", "lastName": "O'Hanlon", "facebook_id": 718469082},
                "organisation": {
                    "type": "organisation",
                    "UUID": "organisation_1",
                    "id": 1,
                    "name": "Tearfund",
                    "description": "When disasters strike, Tearfund responds quickly. Inspired by the example of Jesus, we are working to tackle material and spiritual poverty in more than 50 countries from the inside out.",
                    "administratorEmail": "peter.yates@tearfund.org",
                    "addressLineOne": "100 Church Road",
                    "city": "Teddington",
                    "postalCode": "TW11 8QE",
                    "telephoneNumber": "02089437973",
                    "mobileNumber": "07576016847",
                    "countryCode": "GB",
                    "hasLogo": true,
                    "hasImage": true,
                    "createdAt": "2013-10-02T13:56:34+0000",
                    "updatedAt": "2014-10-02T13:56:34+0000",
                    "isActive": true
                },
                "isGivable": false,
                "prayerCount": 0,
                "type": "organisation",
                "baseType": "organisation"
            },
            {
                "id": 9,
                "account": {"id": 1, "firstName": "Nathan", "lastName": "O'Hanlon", "facebook_id": 718469082},
                "organisation": {
                    "type": "organisation",
                    "UUID": "organisation_1",
                    "id": 1,
                    "name": "Tearfund",
                    "description": "When disasters strike, Tearfund responds quickly. Inspired by the example of Jesus, we are working to tackle material and spiritual poverty in more than 50 countries from the inside out.",
                    "administratorEmail": "peter.yates@tearfund.org",
                    "addressLineOne": "100 Church Road",
                    "city": "Teddington",
                    "postalCode": "TW11 8QE",
                    "telephoneNumber": "02089437973",
                    "mobileNumber": "07576016847",
                    "countryCode": "GB",
                    "hasLogo": true,
                    "hasImage": true,
                    "createdAt": "2013-10-02T13:56:34+0000",
                    "updatedAt": "2014-10-02T13:56:34+0000",
                    "isActive": true
                },
                "isGivable": false,
                "prayerCount": 0,
                "type": "organisation",
                "baseType": "organisation"
            },
            {
                "id": 10,
                "account": {"id": 1, "firstName": "Nathan", "lastName": "O'Hanlon", "facebook_id": 718469082},
                "organisation": {
                    "type": "organisation",
                    "UUID": "organisation_1",
                    "id": 1,
                    "name": "Tearfund",
                    "description": "When disasters strike, Tearfund responds quickly. Inspired by the example of Jesus, we are working to tackle material and spiritual poverty in more than 50 countries from the inside out.",
                    "administratorEmail": "peter.yates@tearfund.org",
                    "addressLineOne": "100 Church Road",
                    "city": "Teddington",
                    "postalCode": "TW11 8QE",
                    "telephoneNumber": "02089437973",
                    "mobileNumber": "07576016847",
                    "countryCode": "GB",
                    "hasLogo": true,
                    "hasImage": true,
                    "createdAt": "2013-10-02T13:56:34+0000",
                    "updatedAt": "2014-10-02T13:56:34+0000",
                    "isActive": true
                },
                "isGivable": false,
                "prayerCount": 0,
                "type": "organisation",
                "baseType": "organisation"
            },
            {
                "id": 11,
                "account": {"id": 1, "firstName": "Nathan", "lastName": "O'Hanlon", "facebook_id": 718469082},
                "organisation": {
                    "type": "organisation",
                    "UUID": "organisation_1",
                    "id": 1,
                    "name": "Tearfund",
                    "description": "When disasters strike, Tearfund responds quickly. Inspired by the example of Jesus, we are working to tackle material and spiritual poverty in more than 50 countries from the inside out.",
                    "administratorEmail": "peter.yates@tearfund.org",
                    "addressLineOne": "100 Church Road",
                    "city": "Teddington",
                    "postalCode": "TW11 8QE",
                    "telephoneNumber": "02089437973",
                    "mobileNumber": "07576016847",
                    "countryCode": "GB",
                    "hasLogo": true,
                    "hasImage": true,
                    "createdAt": "2013-10-02T13:56:34+0000",
                    "updatedAt": "2014-10-02T13:56:34+0000",
                    "isActive": true
                },
                "isGivable": false,
                "prayerCount": 0,
                "type": "organisation",
                "baseType": "organisation"
            }
        ]

## Single PrayerTodayCard [/app_test.php/api/prayer/quiettimes/{quiettime_id}/todays/{id}]
A single PrayerTodayCard object with all its details

+ Parameters

    + quiettime_id (required, number, `1`) ... Numeric `id` of the QuietTime which the prayerTodayCard is within. Has example value.
    + id (required, number, `1`) ... Numeric `id` of the PrayerTodayCard to perform action with. Has example value.

### Retrieve a single PrayerUpdateCard [GET]
+ Request (application/json)

    + Header

            Cookie: PHPSESSID=g89b82eti4oeu6v0c05rq8qng5

+ Response 200 (application/json)

        {
            "id": 1,
            "account": {
                "id": 1,
                "firstName": "Nathan",
                "lastName": "O'Hanlon",
                "facebook_id": 718469082
            },
            "prayerBlock": {
                "id": 1,
                "text": "Do not judge, or you too will be judged. For in the same way you judge others, you will be judged, and with the measure you use, it will be measured to you.",
                "prayerUpdate": false,
                "bookName": "Matthew",
                "chapterFrom": 7,
                "chapterTo": 7,
                "verseFrom": 1,
                "verseTo": 2
            }, 
            "isGivable": false,
            "type": "bible",
            "baseType": "prayer_block"
        }


## PrayerUpdateCards prayers [/app_test.php/api/prayer/quiettimes/{quiettime_id}/todays/{id}/prayers]

+ Parameters

    + quiettime_id (required, number, `1`) ... Numeric `id` of the QuietTime which the prayerTodayCard is within. Has example value.
    + id (required, number, `2`) ... Numeric `id` of the PrayerTodayCard to perform action with. Has example value.

### Retrieve a today cards prayers [GET]
+ Request (application/json)

    + Header

            Cookie: PHPSESSID=g89b82eti4oeu6v0c05rq8qng5

+ Response 200 (application/json)

        {
            "total": 2,
            "data": [
                {
                    "id": 1,
                    "account": {"id": 1, "firstName": "Nathan", "lastName": "O'Hanlon", "facebook_id": 718469082},
                    "prayerCount": 3,
                    "createdAt": "2014-10-02T16:16:41+0000",
                    "prayerUpdate": {"id": 2}
                },
                {
                    "id": 2,
                    "account": {"id": 2, "firstName": "Rupert", "lastName": "Edwards", "facebook_id": 34650},
                    "prayerCount": 2,
                    "createdAt": "2014-10-02T16:16:41+0000",
                    "prayerUpdate": {"id": 2}
                }
            ]
        }

