FORMAT: 1A
HOST: http://local.lepton.co

# SpiritLabs API
PrayerUpdate API is a resource to add prayer updates, as well as comments.

# Group Prayer Updates
PrayerUpdate related resources of the **PrayerUpdates API**

## Prayer Update Collection [/app_test.php/api/prayer/updates]
### List all Prayer Updates for a logged in user [GET]

+ Request (application/json)

    + Header

            Cookie: PHPSESSID=suf8n31ca43dc4ne5h38ok0da5
            Accept: application/json

+ Response 200 (application/json)

        {
          "total": 3,
          "limit": 10,
          "data": [
            {
              "id": 2,
              "account": {
                "id": 1,
                "firstName": "Nathan",
                "lastName": "O'Hanlon",
                "facebook_id": 718469082
              },
              "content": "Second for user 1 prayer update",
              "comments": [
                {
                  "id": 1,
                  "account": {
                    "id": 1,
                    "firstName": "Nathan",
                    "lastName": "O'Hanlon",
                    "facebook_id": 718469082
                  },
                  "content": "First test prayer comment",
                  "createdAt": "2014-08-21T15:30:09+0000"
                },
                {
                  "id": 2,
                  "account": {
                    "id": 1,
                    "firstName": "Nathan",
                    "lastName": "O'Hanlon",
                    "facebook_id": 718469082
                  },
                  "content": "Second test prayer comment",
                  "createdAt": "2014-08-21T15:30:09+0000"
                }
              ],
              "createdAt": "2014-08-21T15:30:09+0000"
            },
            {
              "id": 1,
              "account": {
                "id": 1,
                "firstName": "Nathan",
                "lastName": "O'Hanlon",
                "facebook_id": 718469082
              },
              "content": "Some test prayer update",
              "organisationBase": {
                "id": 1,
                "name": "St George's",
                "countryCode": "GB",
                "colour": "38373E",
                "createdAt": "2014-08-21T15:30:09+0000",
                "updatedAt": "2014-08-21T15:30:09+0000",
                "isActive": true
              },
              "comments": [],
              "createdAt": "2014-08-21T15:30:09+0000"
            }
          ]
        }

## PrayerUpdate Collection with Parameters [/app_test.php/api/prayer/updates?object_id=1&object_type=account&limit=1]
### List all PrayerUpdates for a given account [GET]
There will be the ability to have object_type of 'account' (default), 'organisation', or 'church'. For now just 'account' is supported.

The limit defaults to 10 if not specified. The most recent prayer update will be returned if specified as 1.

+ Request (application/json)

    + Header

            Cookie: PHPSESSID=suf8n31ca43dc4ne5h38ok0da5
            Accept: application/json

+ Response 200 (application/json)

        {"total": 4, "limit": 1, "data": [
            {
                "id": 2,
                "account": {
                    "id": 1,
                    "firstName": "Nathan",
                    "lastName": "O'Hanlon",
                    "facebook_id": 718469082
                },
                "content": "Second for user 1 prayer update",
                "comments": [
                    {
                        "id": 1,
                        "account": {
                            "id": 1,
                            "firstName": "Nathan",
                            "lastName": "O'Hanlon",
                            "facebook_id": 718469082
                        },
                        "content": "First test prayer comment",
                        "createdAt": "2014-08-05T13:07:22+0000"
                    },
                    {
                        "id": 2,
                        "account": {
                            "id": 1,
                            "firstName": "Nathan",
                            "lastName": "O'Hanlon",
                            "facebook_id": 718469082
                        },
                        "content": "Second test prayer comment",
                        "createdAt": "2014-08-05T13:07:22+0000"
                    }
                ],
                "createdAt": "2014-08-05T13:07:22+0000"
            }
        ]}

### Create a PrayerUpdate [POST]
+ Request (application/json)

    + Header

            Cookie: PHPSESSID=suf8n31ca43dc4ne5h38ok0da5

    + Body

            { "content": "A new prayer update" }

+ Response 200 (application/json)

        {"id": 18, "account": {
            "id": 217,
            "firstName": "Nathan",
            "lastName": "O'Hanlon",
            "facebook_id": 718469082
        }, "content": "A new prayer update", "comments": [], "createdAt": "2014-07-09T10:48:58+0000"}

## Single PrayerUpdate [/app_test.php/api/prayer/updates/{id}]
A single PrayerUpdate object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the PrayerUpdate to perform action with. Has example value.

### Retrieve a PrayerUpdate [GET]
+ Request (application/json)

    + Header

            Cookie: PHPSESSID=suf8n31ca43dc4ne5h38ok0da5

+ Response 200 (application/json)

        {"id": 1, "account": {
            "id": 1,
            "firstName": "Nathan",
            "lastName": "O'Hanlon",
            "facebook_id": 718469082
        }, "content": "Some test prayer update", "organisationBase": {
            "id": 1,
            "name": "St George's",
            "countryCode": "GB",
            "colour": "38373E",
            "createdAt": "2014-08-21T15:30:09+0000",
            "updatedAt": "2014-08-21T15:30:09+0000",
            "isActive": true
        }, "comments": [], "createdAt": "2014-08-21T15:30:09+0000"}

### Update a PrayerUpdate [PATCH]
+ Request (application/json)

    + Header
    
            Cookie: PHPSESSID=suf8n31ca43dc4ne5h38ok0da5

    + Body
    
            { "op": "replace", "path": "content", "value": "An updated prayer update" }

+ Response 204 (text/plain; charset=UTF-8)

### Remove a PrayerUpdate [DELETE]

+ Parameters
    + id (required, number, `3`) ... Numeric `id` of the PrayerUpdate to perform delete with. Has example value.

+ Response 204 (text/plain; charset=UTF-8)










# Group Comments
PrayerUpdateComment related resources of the **PrayerUpdateComment API**

## Comments Collection [/app_test.php/api/prayer/updates/2/comments]
### List all Comments for a PrayerUpdate [GET]
+ Request (application/json)

    + Header

            Cookie: PHPSESSID=g89b82eti4oeu6v0c05rq8qng5
            Accept: application/json

+ Response 200 (application/json)

        {"total": 2, "limit": 10, "data": [
            {
                "id": 2,
                "account": {
                    "id": 1,
                    "firstName": "Nathan",
                    "lastName": "O'Hanlon",
                    "facebook_id": 718469082
                },
                "prayerUpdate": {},
                "content": "Second test prayer comment",
                "createdAt": "2014-08-26T11:26:35+0000"
            },
            {
                "id": 1,
                "account": {
                    "id": 1,
                    "firstName": "Nathan",
                    "lastName": "O'Hanlon",
                    "facebook_id": 718469082
                },
                "prayerUpdate": {},
                "content": "First test prayer comment",
                "createdAt": "2014-08-26T11:26:35+0000"
            }
        ]}

### Create a Comment [POST]
+ Request (application/json)

    + Header

            Cookie: PHPSESSID=g89b82eti4oeu6v0c05rq8qng5
            Accept: application/json
            
    + Body
    
            { "content": "A new comment for prayer update 2" }

+ Response 200 (application/json)

        {
            "id": 3,
            "account": {
                "id": 1
            },
            "prayerUpdate": {
                "id": 2,
                "account": {
                    "id": 1
                }
            },
            "content": "A new comment for prayer update 2",
            "createdAt": "2014-08-27T08:00:10+0000"
        }

## Comment [/app_test.php/api/prayer/updates/2/comments/{id}]
A comment object with all of its details

+ Parameters
    + id (required, number, `2`) ... Numeric `id` of the Comment to perform action with. Has example value.

### Retrieve a Comment [GET]
+ Response 200 (application/json)

        {
            "id": 2,
            "prayerUpdate": {
                "id": 2
            },
            "content": "Second test prayer comment",
            "createdAt": "2014-07-10T11:40:22+0000"
        }

### Update a Comment [PATCH]
+ Request (application/json)

    + Header
    
            Cookie: PHPSESSID=g89b82eti4oeu6v0c05rq8qng5

    + Body
    
            { "op": "replace", "path": "content", "value": "An updated comment for prayer update 1" }

+ Response 204

### Remove a Comment [DELETE]
+ Response 204










# Group AccountPrayed
AccountPrayed API is a resource to add and view a record of people who have prayed for a prayer update.

## AccountPrayed Collection [/app_test.php/api/prayer/updates/2/accountprayers]
### List all AccountPrayed objects for a PrayerUpdate [GET]

+ Request (application/json)

    + Header

            Cookie: PHPSESSID=g89b82eti4oeu6v0c05rq8qng5
            Accept: application/json

+ Response 200 (application/json)

        {"total": 1, "limit": 10, "data": [
            {
                "id": 5,
                "prayerUpdate": {
                    "id": 46
                },
                "account": {
                    "id": 245,
                    "firstName": "Nathan",
                    "lastName": "O'Hanlon",
                    "facebook_id": 718469082
                },
                "prayerCount": 3,
                "createdAt": "2014-07-10T11:40:22+0000"
            }
        ]}

### Create a AccountPrayed object [POST]

+ Request (application/json)

    + Header

            Cookie: PHPSESSID=g89b82eti4oeu6v0c05rq8qng5
            Accept: application/json

+ Response 204

## AccountPrayed [/app_test.php/api/prayer/updates/1/accountprayers/{id}]
A single AccountPrayed object for deletion

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the AccountPrayed to perform action with. Has example value.


### Remove a AccountPrayed object [DELETE]

+ Request (application/json)

    + Header

            Cookie: PHPSESSID=g89b82eti4oeu6v0c05rq8qng5
            Accept: application/json

+ Response 204
